### ISSUE TITLE
Failed to parse as JSON

### ISSUE THREAD

**Issue by ivardensphere** [superzanti/ServerSync#51]
Hello, 

This addition is a godsend for pack creators on a server so thank you.

I ran into just one error:
File: EngineersWorkshop-1.1.5-1.10.2.jar failed to parse as JSON

Out of 100+ mods this was the only one that caught an exception when running it server side.

Thanks.

**Comment by rheimus** [comment]
Aye, haven't had much of a chance to look into why EngineersWorkshop fails. Presumably it uses something in its config that is an invalid character.

This will not stop serversync from synchronizing the mod though, it just falls back to comparing the file via hash rather than the version registered in mcmod.info

**Comment by rheimus** [comment]
EWorkshop has a trailing comma at the end of his mcmod.info file.

**Comment by ivardensphere** [comment]
Ah that explains it. Thanks for looking into this. Much appreciated!
