### ISSUE TITLE
Adding files to ignore lists have caused configs between client and server desync cosmetic error

### ISSUE THREAD

**Issue by DPxKnightxZero** [superzanti/ServerSync#6]
When I update now using latest version 2.1 I noticed it claims the configs are not the same though I have check them several times and they are 100 percent the same. It however does not fail to load it just says an error when there isn't one so I believe as of right now that this glitch is purely cosmetic.

**Comment by superzanti** [comment]
This is not a glitch, this is by nature of some of the mods. Some mods change their config files based on weather or not they are a client or server. Either add these files to the ignore list or Download the latest version of my mod to fix this.

This adds a feature where in the server's serversync.cfg there is a value called LAST_UPDATE.
If the client side does not match this value it updates, otherwise it skips the update process.

**Comment by DPxKnightxZero** [comment]
Oh alright no problem.

**Comment by superzanti** [comment]
I hope this new 'LAST_UPDATE' feature is a good solution for you.

**Comment by DPxKnightxZero** [comment]
It seems to work :) I am sorry if I seem like a pain I know what it means to work super hard at something and then notice small oppses ... thank you very much for helping me get the mod to work.

**Comment by superzanti** [comment]
No, thank you for helping me find some bugs :D

**Comment by DPxKnightxZero** [comment]
I have teamspeak3 for the gaming community would like to join? I have Thutmose come on every now and then. He the creator of Pokecube. I mean you can pretty much always find me there XD
